:eye: Trust but verify
tallyhowallet/extension pull request #1840
Opened 2022-07-25 16:53 UTC by mhluongo

Add a warning when interacting with assets whose metadata has been inferred from transaction history.

Refs #1021

2022-07-29 20:57 UTC, mhluongo commented
@Shadowfiend would love your thoughts on how to make this consistent with your plans in https://github.com/tallycash/extension/pull/1788

I'd like to add an "internal" token list for each user in a future PR, and use that to track custom assets going forward. But in the meantime, this PR should be enough to show discovered assets and warn people of scams... except they won't currently show up at all with after this change

https://github.com/tallycash/extension/pull/1788/files#diff-b0e4a7036b74ef74bb2061264a7470aa9dc941d5bb0b326556464bb28480fc80L328

2022-07-30 17:36 UTC, Shadowfiend commented
We already have the internal list--that is what the custom asset stuff is I believe. This todo explains a reasonable path to adding the relevant metadata there:

https://github.com/tallycash/extension/blob/6a69598bdab150ee1c0cebc3b81e05d6369a0fa6/background/services/indexing/index.ts#L294-L299

2022-07-30 17:40 UTC, greg-nagy commented
I think we have started using custom assets for assets with 0 balance at some point.

2022-08-01 19:58 UTC, mhluongo commented
Taking a different tack: this PR shows a warning for any asset in the asset list that isn't on a token list.

It appears that these assets are no longer auto-discovered from the asset transfer call as of #1788... given that we have a warning now, should I [revert part of that PR](https://github.com/tallycash/extension/pull/1788/files#diff-b0e4a7036b74ef74bb2061264a7470aa9dc941d5bb0b326556464bb28480fc80L328) here?

2022-08-03 05:57 UTC, greg-nagy commented
Yes, I think this is the way. 

Nit: I wouldn't revert that change but reintroduce a modified version [according to this comment](https://github.com/tallycash/extension/blob/main/background/services/indexing/index.ts#L294-L299)

2022-08-03 16:23 UTC, Shadowfiend commented
I think two paths we can take here and it's ultimately a product decision. We can nuke the baseline trust concept, always display the warning for non-token list assets without a way to mark them trusted, then separately add a warning dismissal path that adds the token to the custom token list. Or we can land this, invisible because those assets are never added, and then fill out the trust concept as per the TODO and attach the warnings to that. 

Either way works for me.

2022-08-07 00:50 UTC, mhluongo commented
I think the former is the shorter path, but will confirm.

Getting to more token balances in the wallet sooner is going to be a big win for users.

2022-08-07 02:25 UTC, mhluongo commented
@mr-michael calling your attention here: merging this PR means we'll pick up all / nearly all token balances at the risk of including scam tokens, though they'll have clear and obvious warnings.

My thought is we merge this, then do the next bit (allowing tokens to be flagged as trusted or ignored) in a future PR / release based on other priorities. I think that's the right call because it immediately improves the UX for **new** wallets. It can degrade UX a bit for older wallets like mine with a bunch of spam tokens, but most users seem to be onboarding with new accounts.

2022-08-07 02:26 UTC, mhluongo commented
@Shadowfiend @greg-nagy I opened https://github.com/tallycash/extension/issues/1893 to continue the asset trust discussion and unify the two approaches.

2022-08-09 10:38 UTC, jagodarybacka commented on ui/components/Wallet/AssetListItem/CommonAssetListItem.tsx
> +  const baseAsset = !("homeNetwork" in assetAmount?.asset)
Have you tested it with both ETH and MATIC? I've seen cases where `homeNetwork` was missing in base asset 😞

2022-08-11 20:36 UTC, mhluongo commented on ui/components/Wallet/AssetListItem/CommonAssetListItem.tsx
> +  const baseAsset = !("homeNetwork" in assetAmount?.asset)
I have! I'd love another look though if you have a minute.

In the case of `MATIC`, there's an ERC-20 with a `homeNetwork` and a base asset without one... could that be the confusion @jagodarybacka?

2022-08-12 07:09 UTC, jagodarybacka commented on ui/components/Wallet/AssetListItem/CommonAssetListItem.tsx
> +  const baseAsset = !("homeNetwork" in assetAmount?.asset)
hmmmm, yeah, that is the mistake I made probably 😂

2022-08-12 14:46 UTC, 0xDaedalus reviewed
Code looks good to me - waiting on product input before merging

2022-08-16 14:07 UTC, greg-nagy approved these changes
lookin' good, let's ship

2022-12-12 12:54 UTC, jagodarybacka requested changes
- let's add translations
- let's find a better position for this icon, maybe on the right side with send and swap icons? cc @VladUXUI 
![image](https://user-images.githubusercontent.com/20949277/207049907-77b7e506-7c53-465a-8ba5-da090dfb6ae4.png)

2022-12-12 12:54 UTC, jagodarybacka commented on ui/components/Wallet/AssetWarningSlideUp.tsx
> +function TitledSlideUpMenu(props: TitledSlideUpProps): ReactElement {
I think either we can include it in the `AssetWarningSlideUp` or we can add an option of having a title to `SharedSlideUpMenu`. Or make it a separate component?

2022-12-12 12:56 UTC, jagodarybacka commented on ui/components/Wallet/AssetWarningSlideUp.tsx
> +      <SharedButton size="medium" type="secondary" id="close_asset_warning">
There is no "onClick" on this button

2022-12-14 16:04 UTC, jagodarybacka commented
Let's add a feature flag here too

2022-12-21 16:11 UTC, jagodarybacka commented on ui/components/Wallet/AssetWarningSlideUp.tsx
> +function TitledSlideUpMenu(props: TitledSlideUpProps): ReactElement {
Done in a different PR by @kkosiorowska, will be unified - depends on which PR will be merged first

2022-12-22 10:31 UTC, jagodarybacka requested changes
This needs more discussion about the approach as the current solution is draining the network resources

2022-12-22 10:31 UTC, jagodarybacka commented on background/services/indexing/index.ts
> +            this.addTokenToTrackByContract(
I've tested it a little bit more and we have a problem here because even for smaller wallets this method is causing WAY too many requests, it is causing UNS to reject requests, it is throwing an "insufficient resources" chrome error.

To reproduce:
- add a console log here 
- add a wallet, (tested on `berrry.eth` and `mhluongo.eth`) open Polygon network 
- in the background script console you will see the avalanche of errors after ~1min or less

2023-01-04 21:06 UTC, 0xDaedalus commented
Found the issue (took forever!), fixed the issue, added regression tests.  Should be ready for another look @jagodarybacka ✅

2023-01-05 10:06 UTC, jagodarybacka requested changes
It's no longer draining resources but I see there is some problem with base assets as they are sometimes marked as unverified, noticed it for ETH on Optimism and Matic on Polygon 
![image](https://user-images.githubusercontent.com/20949277/210754354-b8b554a3-697e-43c7-8a07-e4a5d29cd672.png)

2023-01-05 18:00 UTC, 0xDaedalus commented
Should be good for another look - note that AVAX on polygon is displayed as untrusted because it is indeed not on the official polygon tokenlist that we use.  Otherwise, network base assets erroneously showing as untrusted should be fixed.

2023-01-06 13:55 UTC, jagodarybacka commented
Hmm 😞 
<img width="386" alt="image" src="https://user-images.githubusercontent.com/20949277/211026238-c01519d3-624f-4242-b5fe-44381e41d42b.png">

2023-01-12 12:36 UTC, jagodarybacka commented
For reference - reproduction steps:

https://user-images.githubusercontent.com/20949277/212067677-8278e920-e1bf-4464-94e8-1ca59df03d10.mov

After account is fully loaded it seems to be fixed:
![image](https://user-images.githubusercontent.com/20949277/212068006-36cc5f08-ed27-48bf-aa23-ff924df96749.png)

Problem here is because `MATIC` token doesn't contain `coinType` property and because of it it is not considered base asset.

2023-01-12 19:11 UTC, merged