blockPricesAlarm tests.
tallyhowallet/extension pull request #2348
Opened 2022-09-30 18:28 UTC by 0xDaedalus

This PR adds a test around the blockPricesAlarm and moves the active network gating of polling for block prices up to the alarm function rather than the `pollBlockPricesPerNetwork` itself.

### To Test
- [ ] Tests should pass
- [ ] Networks should correctly stop being queried for block prices after the `NETWORK_POLLING_TIMEOUT` has elapsed.

2022-10-04 14:24 UTC, greg-nagy requested changes
I love these testing prs

This test as failing now, probably because of changes that came later in time.

2022-10-04 14:24 UTC, greg-nagy commented on background/services/chain/tests/index.unit.test.ts
> +        }
```suggestion
        const ChainServiceExternalized =
          chainService as unknown as ChainServiceExternalized

        ChainServiceExternalized.lastUserActivityOnNetwork = {
          [ETHEREUM.chainID]: Date.now(),
          [POLYGON.chainID]: sixMinsAgo,
          [OPTIMISM.chainID]: sixMinsAgo,
        }
        ;[ETHEREUM, POLYGON, OPTIMISM].forEach((network: EVMNetwork) => {
          ChainServiceExternalized.subscribedNetworks.push({
            network,
            provider: {} as unknown as SerialFallbackProvider,
          })
        })
```

This breakds the indexing/tests/index.unit.test.ts` with `IndexingService › service start › should update cache once token lists load`. Probably there is some state persisting in the mocks. Didn't dig to the end.

2022-10-07 02:37 UTC, 0xDaedalus commented
Have not forgotten about this - there are just a few more testing and alarm related PRs that I'd like to merge before diving in here

2022-10-20 13:08 UTC, greg-nagy commented
The time is ripe 🍎 @0xDaedalus

2023-01-12 19:36 UTC, 0xDaedalus commented
A bit too stale to fixup - will revisit in future

2023-01-12 19:36 UTC, closed without merging