Tabbed onboarding implementation
tallyhowallet/extension pull request #2510
Opened 2022-10-26 12:34 UTC by zuuring

### Notes

This is the initial commit setting up the tabbed onboarding design into the front-end
- Added new CSS & images to reflect design
- Changed initial intro flow to match design
- Still WIP and will update notes accoridingly 

### Demo

https://user-images.githubusercontent.com/7145746/198027131-72b32010-e8e0-4360-bd68-31999fcf0bdc.mp4

2022-12-05 06:55 UTC, hyphenized requested changes
Great work so far! The breathing gradient looks very good, still testing the import seed flow but haven't found issues with it so far 🚀 

Some additional comments and questions:

- Based on the design, I believe background and gradients should be in the body and the right panel should be above a semi transparent dark overlay. We can also move forward with the current design depending on what @VladUXUI says.

- We should use `px` as css units to be consistent with the rest of the codebase (though we should probably consider using `rem` for font sizes).

- Left panel content should change depending on the current route/page

- I think this will be initially released behind a feature flag, so we should make sure to conditionally apply changes that could affect the current onboarding flow.

- `doggo_gold@2x.png` is not being used anywhere

- We might be able to use `currentColor` in (import, ledger, preview).svg

- Can we use svgs for supported chains images?

2022-12-05 06:55 UTC, hyphenized commented on ui/pages/Onboarding/VerifySeed/SeedVerification.tsx
> +          width: 45%;
Not sure if we want to use % here, it could affect spacing as the screen expands or shrinks. It might be safer if we stick to a fixed width

2022-12-05 09:04 UTC, VladUXUI commented
> * Based on the design, I believe background and gradients should be in the body and the right panel should be above a semi transparent dark overlay. We can also move forward with the current design depending on what @VladUXUI says.

That is correct @hyphenized! good eye :D
We changed to having it only on the right side because if we have it on the full page, then the gradient would reset from one page to another (as far as i'm told) and that will be shocking.
If we can change to the above easily, i'm down for that. Otherwise we can leave as is

2022-12-05 12:47 UTC, greg-nagy commented
A note here that we are finishing this PR and pushing it to mergeable state

2022-12-13 14:04 UTC, jagodarybacka reviewed
That's huge 😱 🔥🔥🔥
 
Some initial comments: 
- some of the new icons/images are duplicated (doggo are duplicated, networks logos already existed I think)

2022-12-13 14:44 UTC, VladUXUI commented on ui/pages/Onboarding/Tabbed/ImportSeed.tsx
> +          height: 200px;
Small thing, but this can be cut down to 104px

2022-12-13 14:44 UTC, VladUXUI commented on ui/_locales/en/messages.json
> +        "importSeed": {
Based on feedback from LJ, let's change the content here to:
"subtitle": "Paste or type your 12 to 24 word secret recovery phrase below.",
 "inputLabel": "Input recovery phrase"

2022-12-13 14:48 UTC, VladUXUI commented
Looking very nice @hyphenized !
3 questions:
- Can we add back button to password page?
- Can i switch from 1 input to the other by pressing tab only once in PW page? (right now i have to press twice)
- We removed the background gradient animation? 😢

2022-12-13 16:37 UTC, 0xDaedalus reviewed
No hard blockers here - This PR is big enough where it might make sense to create follow-on issues on whatever you can't address in a quick commit and complete those later.  

I've gone ahead and cleaned up and edited the description of this PR to cleanup the `Onboarding Revamp` milestone once its merged - as well as added a few issues to the milestone found while reviewing.

2022-12-14 13:03 UTC, jagodarybacka requested changes
With `SUPPORT_TABBED_ONBOARDING=false`:

- [x] Something is wrong with styles here, I can't click anything 
![image](https://user-images.githubusercontent.com/20949277/207599108-0584f5c6-5b89-43d3-88da-fe610a000d63.png)
---
With `SUPPORT_TABBED_ONBOARDING=true`:

- [ ] these arrows are not pointing to anything on wide screens
![image](https://user-images.githubusercontent.com/20949277/207599904-0b4547bb-5ef8-4b5b-9fe0-2a938ec6f002.png)

- [ ] Gitcoin bounty link moves to tally website
![image](https://user-images.githubusercontent.com/20949277/207599932-8b151b99-1639-4834-964b-16debc4e7bcb.png)

- [x] missing translation
![image](https://user-images.githubusercontent.com/20949277/207600014-a01a401d-4e4e-40b2-a019-a90727b8c60e.png)

- [x] there is no "submit" button here - weird UX
![image](https://user-images.githubusercontent.com/20949277/207600269-2abda66d-bf24-4276-a2ea-dc4e859bcec2.png)

- [ ] submitting this without a label blows up the whole page 
![image](https://user-images.githubusercontent.com/20949277/207600921-f3a708fd-eccc-48ef-808e-27ef3d847cb6.png)

- [ ] even if I have selected some addresses on the other page there is no possibility to connect selected if there are none selected on current page. Also user can't connect accounts listed on different pages
![image](https://user-images.githubusercontent.com/20949277/207601503-0ed96327-e7fb-4c27-952a-a24561b74b8d.png)

2022-12-15 06:48 UTC, hyphenized commented on ui/components/Shared/SharedButton.tsx
>    iconPosition?: "left" | "right"
Using a jsdoc comment shows a hint in the editor

![image](https://user-images.githubusercontent.com/28708889/207791884-28801977-af9e-4c19-8a65-31debe33d243.png)

2022-12-15 07:31 UTC, hyphenized commented
@VladUXUI 
> 
>     * Can we add back button to password page?
Yes!
>     * Can i switch from 1 input to the other by pressing tab only once in PW page? (right now i have to press twice)
So what's happening is that focus is moving from the password input to the "view password button" and then to the next password input. We can make the focus go from `input1` -> `input2` -> `view password(input1)` -> `view password(input2)` but there's a a11y warning against doing this. It's also possible to make the view password button unreachable by keyboard navigation 👀

> We removed the background gradient animation?

Brand new animated gradient added! ✨ 

@jagodarybacka 

> even if I have selected some addresses on the other page there is no possibility to connect selected if there are none selected on current page. Also user can't connect accounts listed on different pages.

I'm creating a follow up issue for this as it's also the current behaviour as of the latest release

> these arrows are not pointing to anything on wide screens

@VladUXUI can you suggest an approach to this problem? is it alright for the arrows to remain on the right side in these cases?

2022-12-15 07:54 UTC, hyphenized commented on ui/components/Shared/SharedButton.tsx
> +          .center .button_content {
I agree it's confusing, I might be wrong but I feel this button component could use some plumbing. I did not want to modify the base styles for `button_content` as I don't want to risk introducing visual bugs to existing instances of `SharedButton` 😕

2022-12-15 08:05 UTC, hyphenized commented on ui/pages/Onboarding/Tabbed/AddWallet.tsx
> +          {optionsWithSpacer.map((option, i) => {
That's true and definitely would have been cleaner but, since intersperse is common with lists/JSX elements I took this as an opportunity to implement it.

We don't really need to memo these options either. I just think code looks cleaner with `useMemo` than running an IIFE

2022-12-16 15:06 UTC, 0xDaedalus submitted a review, later dismissed
Seeing as how this is feature flagged and there is a fantastic amount of great work in here already - I think we're good to merge this and address the existing concerns in this PR through follow-up issues.

Bravo with this PR - truly well done 👏

2023-01-04 16:08 UTC, jagodarybacka approved these changes
Commits were signed, it's good to go

2023-01-04 16:11 UTC, merged