Fix UI inconsistencies in Swap Page
tallyhowallet/extension pull request #2561
Opened 2022-11-07 07:40 UTC by hyphenized

This PR adds a few React hooks and refactors most of the code that handles swap quotes in the Swap page. Quote requests are now debounced and, if a feature flag is enabled, automatically refresh after a few seconds under certain conditions. 

[ImprovedBartering.webm](https://user-images.githubusercontent.com/28708889/200248932-482759d3-3b7f-4206-ae2a-a0089f817eb9.webm)

Closes #2522

## To Test:
Head to the Swap Page, 
- [ ] Select two assets, input an amount in either field, once you stop typing, the quote should start loading. If you make a correction during load, the last quote data should be reflected on the UI.
- [ ] After flipping the assets, the quote should refresh
- [ ] Changing the target asset should quote the source asset against the target asset amount and vice versa
- [ ] Changing the network should reset both assets
- [ ] Coming from a different page should correctly set initial assets

2022-11-07 13:47 UTC, mhluongo commented
cc @Shadowfiend :smile:

2022-11-08 20:45 UTC, 0xDaedalus reviewed
Quick glance with a few small comments here to get some discussion on this PR going.

I'd also like to flag [that one of the commits](https://github.com/tallycash/extension/pull/2561/commits/1af2fbef619eb126f40af3e78b45e532116ed9b7) has over 600 lines of code changed which is somewhat larger than the typical diff size we would expect for a single commit (although I realize that there is moving of code going on).

I know it is not always convenient to keep commit sizes small (especially when working in a part of the codebase that may be unfamiliar) but I would encourage you to strive for smaller commits as they makes both reviewing and reasoning about the code quite a bit easier.  Looking at the commit message itself it seems like there are certainly some bullet points in there that could have been their own commits.

2022-11-08 20:45 UTC, 0xDaedalus commented on ui/pages/Swap.tsx
> +  const [debouncedRequest] = useState(() => {
Have you considered using [`useDebounce`](https://github.com/tallycash/extension/blob/main/ui/hooks/dom-hooks.ts#L95:L95) here?

2022-11-08 20:45 UTC, 0xDaedalus commented on ui/pages/ApproveQuoteBtn.tsx
> +import React from "react"
This component should probably not be in the `/pages` directory.

2022-11-08 20:45 UTC, 0xDaedalus commented on ui/pages/Swap.tsx
> +  initialSourceAsset?: FungibleAsset | SmartContractFungibleAsset
Should this be `NetworkBaseAsset | SmartContractFungibleAsset`?

2022-11-10 15:44 UTC, 0xDaedalus requested changes
Lots of good stuff here - with some small changes to address.

I'd also like someone else (cc @jagodarybacka @kkosiorowska @greg-nagy) to take a thorough look due to the size of this PR and the fact that it touches the most important part of our application.

I also think that the `SUPPORT_SWAP_QUOTE_REFRESH` flag is awesome and certainly a step in the right direction - but needs a product discussion before we flip it on.

2022-11-10 15:44 UTC, 0xDaedalus commented on ui/pages/Swap.tsx
> +      } finally {
I think we might want a `catch` with some logging here that does not throw instead of a `finally` - I believe this current pattern will silently swallow errors

2022-11-10 15:44 UTC, 0xDaedalus commented on ui/pages/Swap.tsx
> +    type: "getSourceAmount" | "getTargetAmount"
Do you think we should stick with our existing nomenclature of `buyAmount` and `sellAmount`?

2022-11-10 15:44 UTC, 0xDaedalus commented on ui/utils/swap.ts
> +export const fetchQuoteUpdate = async ({
What is the difference between a quote and a quoteUpdate?   Is the initial fetch different from subsequent ones?

2022-11-10 15:44 UTC, 0xDaedalus commented on ui/utils/swap.ts
> +      requestResult.swapTransactionSettings = {
Any particular reason we're favoring immutably updating properties here rather than assigning them directly?

2022-11-10 16:47 UTC, hyphenized commented on ui/pages/Swap.tsx
> +  const [debouncedRequest] = useState(() => {
Yes, but the aim of `useDebounce` seemed to be around debouncing state updates.

2022-11-10 16:48 UTC, hyphenized commented on ui/pages/Swap.tsx
> +    type: "getSourceAmount" | "getTargetAmount"
Yeah... I changed it because I found it confusing with the order of the inputs, but I'm willing to go with what the team feels makes more sense here.

2022-11-10 16:49 UTC, hyphenized commented on ui/utils/swap.ts
> +      requestResult.swapTransactionSettings = {
Good catch! There's no need, was just being extra careful with the original implementation here.

2022-11-11 18:50 UTC, 0xDaedalus commented on ui/utils/swap.ts
> +export const fetchQuoteUpdate = async ({
maybe we just call this `fetchQuote` then?

2022-11-16 16:29 UTC, hyphenized commented on ui/pages/Swap.tsx
> +  initialSourceAsset?: FungibleAsset | SmartContractFungibleAsset
Good catch, I reviewed the code and refactored this type accordingly

2022-11-21 04:29 UTC, hyphenized commented
@0xDaedalus Thank you very much for the feedback! I've rebased this PR to make it easier to review (and understand for future contributors!) and, moved the auto update functionality to a different PR 😄

2022-11-30 01:22 UTC, 0xDaedalus reviewed
So sorry for the late review here - I had left comments but forgot to click `Submit Review` - completely my fault 🙇

2022-12-09 12:23 UTC, jagodarybacka requested changes
Lots of good code here 😍 

Some behaviours I don't like:
- if I enter "0" amount manually the old $ quote is still visible
![image](https://user-images.githubusercontent.com/20949277/206700812-1eb65e28-8db6-4376-9ab8-2a2969588982.png)
- if there are no assets selected I think we can hide "no price info" text
![image](https://user-images.githubusercontent.com/20949277/206701061-808e02d2-50dc-4a5c-8f5c-6907fafdf172.png)
- please update this branch with main so we can see how loading doggo behaves here 🐶

2022-12-09 12:23 UTC, jagodarybacka commented on ui/pages/Swap.tsx
> +                // FIXME: Merge master asset list with account balances.
Are we going to ever do this? I'm not even sure if I understand what this comment is about

2022-12-14 04:33 UTC, hyphenized commented on ui/hooks/react-hooks.ts
> +export function useOnMount<Fn extends (...args: unknown[]) => unknown>(
It's very similar but that hook runs on first render, before the component has mounted

2022-12-14 04:36 UTC, hyphenized commented on ui/pages/Swap.tsx
> +                // FIXME: Merge master asset list with account balances.
Yes, this has already been done by @dills122 in #2628 🚀

2022-12-14 12:01 UTC, jagodarybacka commented
There is a possibility to be stuck in a "Approve asset" state - find some token that will cause "Approve" button to be displayed and change a network

https://user-images.githubusercontent.com/20949277/207590062-cb622810-5839-4782-a80d-83d0f04eca9d.mov

2022-12-16 11:37 UTC, jagodarybacka approved these changes
Works nice! ✅ 

ah no I've found one more thing: I think we should block the button if one of the assets is `0` - but I think there are even more small improvements that could be made here so up to you if you want to do it in this PR or add a task 
![Screenshot 2022-12-16 at 12 50 25](https://user-images.githubusercontent.com/20949277/208092402-79620688-7447-4491-9545-4d0249d0d631.png)

2022-12-21 12:44 UTC, jagodarybacka approved these changes
Now it works great 🎉

2022-12-21 12:48 UTC, merged