dApp -> WalletConnect -> ProviderService flow with v1 support
tallyhowallet/extension pull request #2795
Opened 2022-12-16 11:07 UTC by eladrof

2023-01-20 08:31 UTC, hyphenized requested changes
Looks good! Left a couple of comments, please also fix the linting issues. Tested v1 and v2 flows, injected button does not show up in some modals but connecting manually still works

2023-01-20 08:31 UTC, hyphenized commented on window-provider/wallet-connection-handlers.ts
> +  // observeMutations(addTallyButtonForWalletConnectModal)
Let's read the feature flag directly for now

```suggestion
  if (process.env.SUPPORT_WALLET_CONNECT === "true")
    observeMutations(addTallyButtonForWalletConnectModal)
```

2023-01-20 08:31 UTC, hyphenized commented on background/services/wallet-connect/eip155-request-utils.ts
> +  JsonRpcResult,
We can remove this dependency in favour of using plain objects for results/errors

2023-01-26 09:26 UTC, eladrof commented on background/services/wallet-connect/legacy-sign-client-helper.ts
> +    legacySignClient = new LegacySignClient({ uri })
This is the v1 client
It differs from v2 in lifecycle and functionality so we have no choice but to create and manage both v1 and v2 sign clients separately. We do however end up routing their outputs into a shared pipeline so at least there's that

2023-01-30 18:49 UTC, hyphenized approved these changes
Looks great! Excited to ship this soon!

2023-01-30 19:06 UTC, merged

2023-02-08 16:20 UTC, puppycodes commented
Additional issue needed for WalletConnect QA