☀️ Daylight Abilities Spike
tallyhowallet/extension pull request #2800
Opened 2022-12-16 17:39 UTC by 0xDaedalus

2022-12-20 10:54 UTC, jagodarybacka reviewed
Spike looks great ☀️ I've made some comments going through the code:

2022-12-20 10:54 UTC, jagodarybacka commented on background/main.ts
> +
I think it would be nice to decide what should be the approach to that kind of methods (that are just connectors between redux and services) - should we add methods to the `main` class (like you did here), or should we call services directly in redux slice (not sure if we have this approach anywhere) or should we make redux slice's event emitters (like I did for NFTs)

2022-12-20 10:54 UTC, jagodarybacka commented on background/services/abilities/daylight.ts
> +    `${DAYLIGHT_BASE_URL}/${address}/abilities?type=mint&type=airdrop&type=access`
Is API key not needed?

2022-12-20 10:54 UTC, jagodarybacka commented on background/services/abilities/db.ts
> +    return this.abilities.get({ address, abilityId })
Are you making sure somewhere that the address will have the same format as the one that was added to the DB?

2022-12-20 10:54 UTC, jagodarybacka commented on background/services/abilities/index.ts
> +export type AbilityType = "mint" | "airdrop" | "access"
You have that type already in the [background/services/abilities/daylight.ts](https://github.com/tallyhowallet/extension/pull/2800/files#diff-75c3a55a7960518dffb7cb5b4667f019b326e98842c3adc0fb78232eb1797d30) right?

2022-12-20 10:54 UTC, jagodarybacka commented on background/services/abilities/index.ts
> +      .filter((address, index, self) => self.indexOf(address) === index)
Isn't it just `Set`?

2022-12-20 10:54 UTC, jagodarybacka commented on background/services/abilities/index.ts
> +          this.abilitiesAlarm()
If I remember correctly user has an option to opt-out of the abilities right? Do we plan to stop that alarm then?
Do we even need an alarm for this? Can we fetch abilities based on user's actions in the wallet?

2022-12-20 10:54 UTC, jagodarybacka commented on ui/components/Shared/SharedSlideUpMenu.tsx
> +            background-color: #13302e;
We probably shouldn't do it 😄  Can we just add a new color variable?

2022-12-20 10:54 UTC, jagodarybacka commented on ui/pages/Abilities/AbilityRemovalConfirm.tsx
> +            color: #D6EAE9;
```suggestion
            line-height: 24px;     
            color: #D6EAE9;
```

2022-12-20 14:30 UTC, 0xDaedalus commented on background/services/abilities/daylight.ts
> +    `${DAYLIGHT_BASE_URL}/${address}/abilities?type=mint&type=airdrop&type=access`
there is a free tier that seems to be more than enough for our needs 😄

2022-12-20 14:33 UTC, 0xDaedalus commented on background/services/abilities/index.ts
> +export type AbilityType = "mint" | "airdrop" | "access"
yup but i made this type separate for two reasons:

1. We don't want to support every daylight type in the app (there is a lot of spam)
2. To decouple our internal data model from daylight's (what if we want to add a 'tally' ability in the future)

2022-12-20 14:35 UTC, 0xDaedalus commented on background/services/abilities/index.ts
> +      .filter((address, index, self) => self.indexOf(address) === index)
Indeed - brain fart 😅

2022-12-20 14:37 UTC, 0xDaedalus commented on background/services/abilities/index.ts
> +          this.abilitiesAlarm()
> Do we plan to stop that alarm then?

I think we can add a check in the alarm that prevents it from doing anything

> Do we even need an alarm for this?

The current working plan is to eventually have some type of notification pop up when you are eligible for a new ability.  Decided to init the alarm here with a 60 minute timer with that eventual state in mind.

2022-12-20 14:59 UTC, 0xDaedalus commented on ui/components/Shared/SharedSlideUpMenu.tsx
> +            background-color: #13302e;
Hmmmn looking at the figma file again it looks like `var(--green-95)` is indeed the correct color here - although I SWEAR it was not when I was working on this last week.  Probably a gap in my knowledge of how to use figma - will revert.

2022-12-20 15:00 UTC, 0xDaedalus commented on background/main.ts
> +
Agreed - I have heard complaints that the event emitter pattern is a bit confusing (although I don't personally feel that way) which is why I went with this pattern.  I would _love_ to standardize how we do this - shall we start a thread in #Tech?

2022-12-20 15:19 UTC, 0xDaedalus commented on background/services/abilities/db.ts
> +    return this.abilities.get({ address, abilityId })
Good catch - this was happening implicitly (and we were not normalizing) - so added normalization as well as a way for us to check for these kinds of inconsistencies at compile time going forward.

2022-12-20 19:30 UTC, hyphenized requested changes
<img width="188" alt="image" src="https://user-images.githubusercontent.com/28708889/208749120-a5526a00-5e47-4ecf-a177-5337fe07e7f7.png"/> 

Daylight is here! It's looking good, left some comments!

2022-12-20 19:30 UTC, hyphenized commented on ui/pages/Abilities/AbilityCard.tsx
> +const AbilityCard = ({ ability }: { ability: Ability }): ReactElement => {
```suggestion
function AbilityCard({ ability }: { ability: Ability }): ReactElement {
```

2022-12-21 12:09 UTC, jagodarybacka commented on background/main.ts
> +
We can, I'll set a reminder to go back to this topic next year

2022-12-21 14:57 UTC, 0xDaedalus commented on ui/components/Overview/AbilitiesHeader.tsx
> +          background: url("./images/assets/daylight.png");
Happy to do in a followup

2022-12-22 06:59 UTC, hyphenized approved these changes
Great work on the spike, looks like this is good to go!

2022-12-22 16:12 UTC, merged