Display an error message from an RPC request instead of 'the user rejected the request'
tallyhowallet/extension pull request #2802
Opened 2022-12-19 11:43 UTC by kkosiorowska

Closes #2672 

This PR propagates a real error message to the user.

## Steps to Recreate
- Swap on [Velodrome](https://app.velodrome.finance/swap) (Optimism)
- Make sure that transaction need an approval first 
- Make sure that the approval process passes.
- Next, try to sign the transaction.
- Check if a propagated error is displayed.

2022-12-20 14:28 UTC, 0xDaedalus commented
This is technically not in line with EIP-1193 but i definitely see the value in it.  Curious to hear others thoughts on this.

2022-12-21 12:04 UTC, jagodarybacka reviewed
So do I understand it correctly that because of this change we will be responding to dapps with a message with a possibly modified error code? Isn't it going to break something or cause wrong error handling in the dapp itself?

2022-12-21 15:17 UTC, 0xDaedalus commented
> So do I understand it correctly that because of this change we will be responding to dapps with a message with a possibly modified error code?

The error code _must_ stay the same - but [the spec](https://eips.ethereum.org/EIPS/eip-1193#rpc-errors) dictates that:
```
message SHOULD adhere to the specifications in the Error Standards section below
````
which does specify the description sent along with code 4001.

Especially with the wording of "should" I'm thinking its ok for us to bend the rules here a little bit.

2022-12-22 07:46 UTC, kkosiorowska commented
> So do I understand it correctly that because of this change we will be responding to dapps with a message with a possibly modified error code? Isn't it going to break something or cause wrong error handling in the dapp itself?

Only the message is modified. The change is intended to describe the issues more precisely and it shouldn't break anything. The message is extracted from the error and then displayed in the dapp.

2022-12-22 08:04 UTC, kkosiorowska commented on background/services/provider-bridge/index.ts
> +        // eslint-disable-next-line default-case
> It seems to me like it is not a "switch" if there is no default case + we have to use `true`

It seemed to me that this notation would be clearer and easier to understand. But of course, I can change this into a simple` if` structure.

2022-12-22 12:08 UTC, jagodarybacka submitted a review, later dismissed
I'm ok with bending the rules a little bit if it is not breaking other stuff

2022-12-22 17:18 UTC, 0xDaedalus submitted a review, later dismissed
Lets use this PR as an opportunity to write our first test for the provider-bridge.

2022-12-28 13:40 UTC, kkosiorowska commented
> Lets use this PR as an opportunity to write our first test for the provider-bridge.

I created some first simple tests for provider-bridge.

2023-01-04 04:36 UTC, hyphenized commented on background/services/provider-bridge/index.ts
> +      }
Some of the switch cases can throw errors that are already instances of `EIP1193Error` e.g.: `EIP1193Error(EIP1193_ERROR_CODES.unauthorized)`. If we're not intentionally shadowing those with `EIP1193_ERROR_CODES.userRejectedRequest` we should also handle them correctly in this catch statement.

2023-01-04 14:18 UTC, kkosiorowska commented on background/services/provider-bridge/index.ts
> +      }
Let's also handle this correctly.

2023-01-16 01:15 UTC, hyphenized requested changes
Nice work, I think this is almost ready to be merged. Left a couple of additional comments.

2023-01-16 01:15 UTC, hyphenized commented on background/services/provider-bridge/tests/index.unit.test.ts
> +describe("Provider bridge", () => {
```suggestion
describe("ProviderBridgeService", () => {
```

2023-01-19 20:15 UTC, Shadowfiend reviewed
Left a couple of notes on the casts and type safety here, but it's also worth noting that historically I don't think we've correctly surfaced underlying RPC errors (i.e., if we send an `eth_sendTransaction` and it returns with an error). It feels like that is part of what this is meant to address—but these should be returned *with the underlying RPC error code*! EIP-1193 states:

```
ProviderRpcError codes and messages SHOULD follow these conventions, in order of priority:

1. The errors in the [Provider Errors](https://eips.ethereum.org/EIPS/eip-1193#provider-errors) section below
2. Any errors mandated by the erroring RPC method’s specification
3. The [CloseEvent status codes](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent#Status_codes)
```

(2) is what these errors fall under, and they shouldn't produce a “The user rejected the request” error code. This is a longstanding bug in our implementation of the bridge.

From a “get things done” perspective, I would suggest finishing this off as-is, then seeing if there are error codes we should be passing through instead of replacing with the 4001 code. Super super excited to see this being tackled!

2023-01-19 20:15 UTC, Shadowfiend commented on background/services/provider-bridge/utils.ts
> +export function getRPCErrorResponser(error: unknown): {
Because we're only calling this from our own code, what do you think about making `error` already be a `{ body: string }`, and letting the calling code handle both *checking* that this is the case, and casting to `{ body: string }`? My thinking here is that right now the caller does both the property checks and some of the parsing, so we should bring the casting close to those checks.

2023-01-19 20:15 UTC, Shadowfiend commented on background/services/provider-bridge/utils.ts
> +  const parsedError = JSON.parse((error as { body: string }).body)?.error
Similarly to above, just because we've determined this is a `{ body: string }` at this point, doesn't mean we know that it's parsable as JSON. We think it is, but the compiler won't help us avoid breaking this invariant in the future.

What do you think about wrapping all of this in a `try`/`catch`, and if the JSON parsing fails (or if `parsedError` is `undefined` or `null`!), returning `undefined`. Then the caller can surface a generic error if it can't properly extract the error.

2023-01-23 16:02 UTC, jagodarybacka reviewed
No manual tests yet but couple comments on the code, looking good btw 😊

2023-01-30 18:26 UTC, merged