Update data after transferring last NFT from collection
tallyhowallet/extension pull request #2805
Opened 2022-12-20 14:49 UTC by jagodarybacka

Resolves https://github.com/tallyhowallet/extension/issues/2789

### What
When the last NFT from a given collection is transferred we have to remove the collection from the database and redux slice.

### Testing
- transfer NFTs (you can use OpenSea) between accounts, pick collection that has only one NFT
- check if everything is updated correctly - you can't see the collection or NFT that you transferred

2022-12-20 15:44 UTC, 0xDaedalus commented on background/services/nfts/db.ts
> +  async removeByTransferredNFTs(removedNFTs: TransferredNFT[]): Promise<void> {
This method name is a bit confusing - unclear that someone would be able to tell whats going on in this method by reading the method name

2022-12-21 13:26 UTC, jagodarybacka commented on background/services/nfts/db.ts
> +  async removeByTransferredNFTs(removedNFTs: TransferredNFT[]): Promise<void> {
Do you have a better idea? Maybe `cleanupAfterTransfers`?

2022-12-29 09:39 UTC, kkosiorowska commented on background/redux-slices/nfts_update.ts
> +                  delete immerState.nfts[chainID][normalizedAddress][
We should probably also remove the collection from the filter list

2023-01-02 14:21 UTC, greg-nagy commented on background/services/nfts/db.ts
> +    const collectionIdsToRemove = (await nftsToRemove.toArray()).reduce(
collection ids should be available in the [api's `collection` property.](https://docs.simplehash.com/reference/nfts-by-owners)

Using that value could simplify this part

2023-01-02 14:48 UTC, greg-nagy requested changes
The remove from db function might be buggy and it should have some tests.

The separation of concerns between the db and the service layer is a very nice to have. 
Seems nounced but these small tidbits can add up over time.

2023-01-02 14:48 UTC, greg-nagy commented on background/services/nfts/db.ts
> +      .filter((collection) => collectionIdsToRemove.has(collection.id))
Blocker

How can we be sure that all the NFTs have been removed from the collection? 

Some tests would be useful.

2023-01-02 14:48 UTC, greg-nagy commented on background/services/nfts/db.ts
> +  async removeByTransferredNFTs(removedNFTs: TransferredNFT[]): Promise<void> {
(Soft blocker)

The db layer shouldn't care/know about the fact that these nfts were transfered. 
The db layer should handle only the concern of removing NFTs. 

I would use `removeNFTsByIDArray` and using only the ids array as params.

2023-01-03 13:27 UTC, jagodarybacka commented on background/services/nfts/db.ts
> +    const collectionIdsToRemove = (await nftsToRemove.toArray()).reduce(
I think [SH takes care](https://docs.simplehash.com/reference/nft-model) about making NFT ids unique:
> Unique identifier for an NFT (chain.contract_address.token_id for EVM chains & Flow, chain.mint_address for Solana)

Even if we remove an NFT that is actually still owned by a given account the next step in the whole "NFTs data update" process is to refetch collections - so accidentally removed NFT/collection should be added back to our local data.

2023-01-03 13:48 UTC, jagodarybacka commented on background/services/nfts/db.ts
> +      .filter((collection) => collectionIdsToRemove.has(collection.id))
The problem is that we don't really know if all NFTs were removed as there is no info about the collection state at this point (requesting transfers from SH). In the database, we may not have all NFTs from the given collection (they are not fetched yet).

The idea behind this code was that we will remove the collection if any NFT from this collection was removed - because the next step will be to [refetch all collections](https://github.com/tallyhowallet/extension/blob/nft-detect-transfers-fixes/background/services/nfts/index.ts#L97) so they will be back in the database. 

I see now that this is not clear looking at this method alone so I will think about improving the structure, feel free to give some suggestions 😃

2023-01-03 14:55 UTC, jagodarybacka commented on background/redux-slices/nfts_update.ts
> +                  delete immerState.nfts[chainID][normalizedAddress][
You found a 🐛 !

2023-01-03 15:04 UTC, greg-nagy approved these changes
looks, good, let's 🚚

2023-01-03 15:08 UTC, merged