Filter abilities
tallyhowallet/extension pull request #2926
Opened 2023-01-26 08:02 UTC by kkosiorowska

Closes #2864

This PR adds the ability to filter abilities.  Changes:

- 

## UI

## To Test

## Testing Env
```
SUPPORT_ABILITIES=true
```

Latest build: [extension-builds-2899](https://github.com/tallyhowallet/extension/suites/10592199844/artifacts/527861018) (as of Thu, 26 Jan 2023 07:45:19 GMT).

2023-01-26 22:55 UTC, 0xDaedalus requested changes
Tested and the filtering works great!  I would however like to suggest an alternative implementation of the filters that I think might simplify quite a bit of the logic around getting and filtering abilities.

I think we can represent `type`, `accounts`, and `status` as sets of strings which we persist in redux (think of the "filter state" as the union of these sets).  If we do this - then our "filters" can simply be selectors acting on this "filter state" - meaning our `selectAbilities` selector can be composed of 3 discrete selectors (one for each kind of filter) and we don't need to worry about all of the messy object spread stuff I introduced inside of `selectFilteredAbilities`.  

We also get the added benefit of not needing to worry about the `isEnabled` property filters currently have since we can infer if a filter is enabled by its presence or absence in a given `Set`, or worrying about using `findIndex` since we could use `Set.add` and `Set.delete` (immer should take care of making those operations immutable for us).

2023-01-26 22:55 UTC, 0xDaedalus commented on background/abilities.ts
> +import { NormalizedEVMAddress } from "./types"
I'm not sure if the stuff in here feels like it should have its own file.  We're moving away from using `types.ts` files in the repository and this kind of just feels like a renamed `types.ts` file with a few constants in it.  Also I don't know that it deserves to be at the top level of the `background` folder.

2023-01-26 22:55 UTC, 0xDaedalus commented on background/redux-slices/abilities.ts
> +const typesFilter: FilterType[] = ABILITY_TYPES.map((type) => ({
I think a different approach here could be having a `Set` and filtering based on if a given type is included in the set or not inside of a selector.

This would be a bit cleaner (don't need to worry about the `isEnabled` property) and would let us check if a given ability should be filtered out or not in O(1)

2023-01-26 22:55 UTC, 0xDaedalus commented on background/redux-slices/abilities.ts
> +    accounts: [],
`Set` here as well

2023-01-26 22:55 UTC, 0xDaedalus commented on background/redux-slices/abilities.ts
> +  filters: {
Conceptually I would argue that we only have _one_ filter - and by changing the properties of `state`, `types`, etc... we are changing the properties of that single filter

2023-01-26 22:55 UTC, 0xDaedalus commented on background/redux-slices/abilities.ts
> +      { payload: filter }: { payload: FilterAccount }
I think that we could get some increased clarity here if we named this `Account` rather than `FilterAccount`.  Same with `FilterType`.

2023-01-26 22:55 UTC, 0xDaedalus commented on background/redux-slices/utils/account-filter-utils.ts
> +  thumbnailURL?: string
Why are we naming and giving thumbnails to filters?

2023-01-26 22:55 UTC, 0xDaedalus commented on background/redux-slices/selectors/abilitiesSelectors.ts
> +export const selectHideDescription = createSelector(
```suggestion
export const selectDescriptionHidden = createSelector(
```

2023-01-26 22:55 UTC, 0xDaedalus commented on background/redux-slices/utils/abilities.ts
> +export const filterAbility = (
Love this approach ❤️

2023-01-26 22:55 UTC, 0xDaedalus commented on ui/pages/Abilities.tsx
> +                  ariaLabel={t("filters.title")}
After hovering over this icon, clicking in, and then clicking out - the tooltip sticks.

https://user-images.githubusercontent.com/94649004/214967003-d90757f4-23aa-4a8b-be5d-11d24a4b09bf.mov



Not necessary to fix in this PR

2023-01-26 22:55 UTC, 0xDaedalus commented on background/redux-slices/abilities.ts
> +export type AbilityState = "open" | "closed" | "expired" | "deleted" | "all"
I believe that `closed` should be `completed`

2023-01-26 22:55 UTC, 0xDaedalus commented on background/redux-slices/utils/abilities.ts
> +import { Ability, AbilityType } from "../../abilities"
We 100% need some tests around filtering abilities

2023-01-26 22:55 UTC, 0xDaedalus commented on background/services/abilities/index.ts
> +    normalizedAbilities.push({
@VladUXUI Can you confirm that we want the user to be able to see all ability types?  I thought we had discussed only showing a subset of types that we thought were most likely to be relevant

2023-01-26 22:55 UTC, 0xDaedalus commented on background/abilities.ts
> +  "article",
I am 90% sure we don't want to show articles but will double check with vlad

2023-01-27 08:21 UTC, kkosiorowska commented on ui/pages/Abilities.tsx
> +                  ariaLabel={t("filters.title")}
Yes, the fix is in this https://github.com/tallyhowallet/extension/pull/2899. And it should be merged after it.

2023-01-27 10:21 UTC, kkosiorowska commented on background/abilities.ts
> +import { NormalizedEVMAddress } from "./types"
I wanted to organize the structure. I checked where other services hold types. Types for other services are also at this level like for nfts. I understand that this is the highest level because we refer to it from the services or lib directory. However, I'm not sure where they should be located exactly. Do you have any idea where to put them?

2023-01-27 11:05 UTC, VladUXUI commented on background/services/abilities/index.ts
> +    normalizedAbilities.push({
> @VladUXUI Can you confirm that we want the user to be able to see all ability types? I thought we had discussed only showing a subset of types that we thought were most likely to be relevant

We discussed having some toggled off by default, but they should all be there.
The ones that should be active by default are Mint,Airdrop,Vote,Access. The rest should be toggled off and user can toggle them on if he wants too

2023-01-27 11:29 UTC, kkosiorowska commented on background/services/abilities/index.ts
> +    normalizedAbilities.push({
I will change it.

2023-01-27 11:48 UTC, kkosiorowska commented
> I think we can represent `type`, `accounts`, and `status` as sets of strings which we persist in redux (think of the "filter state" as the union of these sets). If we do this - then our "filters" can simply be selectors acting on this "filter state" - meaning our `selectAbilities` selector can be composed of 3 discrete selectors (one for each kind of filter) and we don't need to worry about all of the messy object spread stuff I introduced inside of `selectFilteredAbilities`.
> 
> We also get the added benefit of not needing to worry about the `isEnabled` property filters currently have since we can infer if a filter is enabled by its presence or absence in a given `Set`, or worrying about using `findIndex` since we could use `Set.add` and `Set.delete` (immer should take care of making those operations immutable for us).

It sounds great. In this approach, there is a problem with non-serializable values. It is possible that this can be fixed however I prefer to make sure that this is definitely what we want to do.

![Screenshot 2023-01-27 at 12 39 18](https://user-images.githubusercontent.com/23117945/215078643-252faec9-4686-4e8e-9a9c-4ddae04f04b1.png)

https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state

2023-01-27 12:09 UTC, kkosiorowska commented
> I think we can represent `type`, `accounts`, and `status` as sets of strings which we persist in redux (think of the "filter state" as the union of these sets). If we do this - then our "filters" can simply be selectors acting on this "filter state" - meaning our `selectAbilities` selector can be composed of 3 discrete selectors (one for each kind of filter) and we don't need to worry about all of the messy object spread stuff I introduced inside of `selectFilteredAbilities`.
> 
> We also get the added benefit of not needing to worry about the `isEnabled` property filters currently have since we can infer if a filter is enabled by its presence or absence in a given `Set`, or worrying about using `findIndex` since we could use `Set.add` and `Set.delete` (immer should take care of making those operations immutable for us).

It sounds great but in this approach, there is a problem with non-serializable values.  Redux best practices don’t recommend this. 

https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state

2023-01-27 14:08 UTC, 0xDaedalus commented
> Redux best practices don’t recommend this.

Ah - fantastic point and one that completely slipped by mind!  I still think that even if we use Array<string> we can get the benefits of:
- Getting rid of the the `isEnabled` property
- Clearer filter composition via multiple selectors
- Not needing the `FilterAccount` type, and simplifying the `FilterType` type into a string enum.

2023-01-30 08:52 UTC, kkosiorowska commented
Ready for another look ✅

2023-01-30 18:12 UTC, 0xDaedalus approved these changes
📈 🎉 💯

2023-01-30 18:12 UTC, merged