Custom RPCs - Update top menu protocol switcher
tallyhowallet/extension pull request #2980
Opened 2023-02-03 08:16 UTC by hyphenized

Closes #2958

Also fixes the issue with the disappearing asset icons

![image](https://user-images.githubusercontent.com/28708889/216546665-122a2583-2663-4e4b-ac42-cc60e33b29cc.png)

## Testing Env

```
SUPPORT_CUSTOM_NETWORKS=true
SUPPORT_CUSTOM_RPCS=true
```

## To Test
- [ ] Head over to [chainlist.org](https://chainlist.org), add a few custom networks
- [ ] Try to switch networks

2023-02-03 09:48 UTC, jagodarybacka reviewed
Looks good, added minor improvements ideas

- Q: that list is hardcoded or will it be dynamic based on the activated networks?
![image](https://user-images.githubusercontent.com/20949277/216567682-63a59c37-763a-4845-899d-cb03281a5983.png)
 
- bottom margin of "Activate..." section is too wide IMO
![image](https://user-images.githubusercontent.com/20949277/216567133-ba137aa6-9aba-4c6b-aa39-7fddb61f4dd4.png)

2023-02-03 09:48 UTC, jagodarybacka commented on ui/components/TopMenu/TopMenuProtocolList.tsx
> +        <ul>
Isn't classnames syntax like:
```suggestion
      <div className={classNames({ "networks_list": customNetworksEnabled })}>
        <ul>
```

2023-02-03 09:48 UTC, jagodarybacka commented on ui/components/TopMenu/TopMenuProtocolListItem.tsx
> +const FALLBACK_ICONS_BY_CHAINID: Record<string, string> = {
I would totally move this list out of the component to some consts file :D

2023-02-03 09:48 UTC, jagodarybacka commented on ui/components/TopMenu/TopMenuProtocolList.tsx
> +        <footer className="custom_rpc_footer">
This footer looks like it can become a separate component

2023-02-03 09:48 UTC, jagodarybacka commented on ui/components/TopMenu/TopMenuProtocolListItem.tsx
> +const FALLBACK_ICONS_BY_CHAINID: Record<string, string> = {
Also there is a SharedNetworkIcon component that could support these icons (it's not used in a lot of places yet but I think there are like 5 more places that can use SharedNetworkIcon). Non-blocking, to be done later ;)

2023-02-04 21:26 UTC, hyphenized commented on ui/components/TopMenu/TopMenuProtocolListItem.tsx
> +const FALLBACK_ICONS_BY_CHAINID: Record<string, string> = {
You're right, thanks! I wonder if we should keep a local copy of these icons within the extension cc @kkosiorowska  @0xDaedalus

2023-02-04 21:27 UTC, hyphenized commented on ui/components/TopMenu/TopMenuProtocolList.tsx
> +        <footer className="custom_rpc_footer">
Great suggestion! It's looking much cleaner now, thanks!

2023-02-04 21:28 UTC, hyphenized commented on ui/components/TopMenu/TopMenuProtocolList.tsx
> +        <ul>
Yes, both ways work since it compacts the parameters array by removing falsy values

2023-02-06 11:17 UTC, jagodarybacka reviewed
In the top ribbon icons for custom chains are missing: 
![image](https://user-images.githubusercontent.com/20949277/216958050-bb0b8d16-22af-46e1-95d8-c3e13fa11a42.png)
but on the list they are fine 
![image](https://user-images.githubusercontent.com/20949277/216958108-f9e27da0-e01b-4c5e-b290-4b24ba41d40f.png)

2023-02-09 12:51 UTC, jagodarybacka requested changes
Works good, let's just remove these unused styles

2023-02-09 12:51 UTC, jagodarybacka commented on ui/utils/networks.ts
> +    Number.parseInt(network.chainID, 10) % NETWORK_COLORS_FALLBACK.length
Smart 🤓

2023-02-09 12:51 UTC, jagodarybacka commented on ui/components/TopMenu/TopMenuProtocolListItem.tsx
> +            background: url(${getNetworkIcon(network)});
we have no `.icon` in this component so it can be removed

2023-02-13 08:49 UTC, kkosiorowska commented on ui/components/TopMenu/TopMenuProtocolListItem.tsx
> +const FALLBACK_ICONS_BY_CHAINID: Record<string, string> = {
I agree with Jagoda, it works well so I think there isn't a need for it.

2023-02-14 16:27 UTC, 0xDaedalus approved these changes
✅

2023-02-14 16:34 UTC, jagodarybacka approved these changes

2023-02-14 16:38 UTC, merged